services:
  db:
    image: postgres:16
    container_name: barberhair_db
    environment:
      POSTGRES_USER: barber
      POSTGRES_PASSWORD: "@Dear2456"
      POSTGRES_DB: BarberHair_DB
    ports:
      - "5432:5432"

    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
